services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    mem_limit: 512m
    cpus: "1.00"
    pids_limit: 256
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=fraud_db;Username=fraud_engine;Password=fraud_engine_dev_password
      - ConnectionStrings__Redis=redis:6379,password=redis_dev_password,abortConnect=false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    mem_limit: 768m
    cpus: "1.00"
    pids_limit: 256
    environment:
      POSTGRES_DB: fraud_db
      POSTGRES_USER: fraud_engine
      POSTGRES_PASSWORD: fraud_engine_dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fraud_engine -d fraud_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    mem_limit: 256m
    cpus: "0.50"
    pids_limit: 128
    command: [ "redis-server", "--requirepass", "redis_dev_password", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "redis_dev_password", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
